name: Node.js CI Build

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Latest stable as of 2025

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Specify your version (e.g., 20 or 22)
        cache: 'npm'

    - name: Install & run build
      run: |
        npm install
        npm run build
